spring:
  datasource:
    url: "$SPRING_DATASOURCE_URL"
    username: "$SPRING_DATASOURCE_USERNAME"
    password: "$SPRING_DATASOURCE_PASSWORD"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
    default-schema: public

jwt:
  secret: secret
  expirationMs: 86400000

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    com.test.task.kuehne.cities.controller: DEBUG
    org.hibernate: INFO